---
:ems:
  :ems_kubernetes:
    :miq_namespace: management-infra
    :image_inspector_registry: docker.io
    :image_inspector_repository: openshift/image-inspector
    :event_handling:
      :event_groups:
        :addition:
          :critical:
            - CONTAINER_CREATED
            - REPLICATOR_SUCCESSFULCREATE
            - REPLICATOR_FAILEDCREATE
        :status:
          :critical:
            - NODE_NODEREADY
            - NODE_NODENOTREADY
            - POD_FAILEDVALIDATION
            - POD_DEADLINEEXCEEDED
            - POD_INSUFFICIENTFREECPU
            - POD_NODESELECTORMISMATCHING
            - POD_SCHEDULED
            - POD_FAILEDSCHEDULING
            - CONTAINER_UNHEALTHY
            - CONTAINER_KILLING
            - CONTAINER_STARTED
            - CONTAINER_STOPPED
        :power:
          :critical:
            - NODE_REBOOTED
            - NODE_NODESCHEDULABLE
            - NODE_NODENOTSCHEDULABLE
        :storage:
          :critical:
            - NODE_FAILEDMOUNT
            - NODE_INVALIDDISKCAPACITY
            - POD_OUTOFDISK
            - POD_INSUFFICIENTFREEMEMORY
        :network:
          :critical:
            - POD_HOSTPORTCONFLICT
    :open_timeout: 60.seconds
    :read_timeout: 60.seconds
  :ems_monitoring:
    :alerts_collection:
      :open_timeout: 10.seconds
      :timeout: 20.seconds
:http_proxy:
  :kubernetes:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :kubernetes:
    :refresh_interval: 15.minutes
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_kubernetes:
        :poll: 1.seconds
    :queue_worker_base:
        :ems_metrics_collector_worker:
          :ems_metrics_collector_worker_kubernetes:
            :metrics_port: 5000
            :metrics_path: "/hawkular/metrics"
        :ems_refresh_worker:
          :ems_refresh_worker_kubernetes: {}
